2022-02-18 11:09:37,757 INFO    MainThread:5845 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 11:09:37,757 INFO    MainThread:5845 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 11:09:37,758 INFO    MainThread:5845 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_110937-1jl8busg/logs/debug.log
2022-02-18 11:09:37,758 INFO    MainThread:5845 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_110937-1jl8busg/logs/debug-internal.log
2022-02-18 11:09:37,758 INFO    MainThread:5845 [wandb_init.py:init():404] calling init triggers
2022-02-18 11:09:37,758 INFO    MainThread:5845 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-18 11:09:37,758 INFO    MainThread:5845 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 26uatppm
2022-02-18 11:09:37,760 INFO    MainThread:5845 [wandb_run.py:finish():1457] finishing run simon-donike/eot_deep-learning-LeNet_v2/26uatppm
2022-02-18 11:09:37,762 INFO    MainThread:5845 [jupyter.py:save_history():429] not saving jupyter history
2022-02-18 11:09:37,762 INFO    MainThread:5845 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-02-18 11:09:37,762 INFO    MainThread:5845 [wandb_init.py:_jupyter_teardown():303] cleaning up jupyter logic
2022-02-18 11:09:37,762 INFO    MainThread:5845 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-18 11:09:37,764 INFO    MainThread:5845 [wandb_run.py:_restore():1752] restore
2022-02-18 11:09:38,301 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 11:09:38,552 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 761
}

2022-02-18 11:09:39,341 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25221
}

2022-02-18 11:09:39,445 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25221
}

2022-02-18 11:09:39,559 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 761
  total_bytes: 25221
}

2022-02-18 11:09:39,662 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}

2022-02-18 11:09:39,765 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}

2022-02-18 11:09:39,867 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}

2022-02-18 11:09:39,970 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}

2022-02-18 11:09:40,073 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}

2022-02-18 11:09:40,175 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}

2022-02-18 11:09:40,705 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}

2022-02-18 11:09:41,164 INFO    MainThread:5845 [wandb_run.py:_wait_for_finish():1912] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 25221
  total_bytes: 25221
}
local_info {
}

2022-02-18 11:09:43,155 INFO    MainThread:5845 [wandb_run.py:_append_files():2180] logging synced files
2022-02-18 11:09:43,161 INFO    MainThread:5845 [wandb_init.py:init():460] starting backend
2022-02-18 11:09:43,161 INFO    MainThread:5845 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-02-18 11:09:43,167 INFO    MainThread:5845 [backend.py:ensure_launched():216] starting backend process...
2022-02-18 11:09:43,340 INFO    MainThread:5845 [backend.py:ensure_launched():222] started backend process with pid: 9669
2022-02-18 11:09:43,342 INFO    MainThread:5845 [wandb_init.py:init():469] backend started and connected
2022-02-18 11:09:43,382 INFO    MainThread:5845 [wandb_run.py:_label_probe_notebook():911] probe notebook
2022-02-18 11:09:43,383 INFO    MainThread:5845 [wandb_run.py:_label_probe_notebook():921] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-02-18 11:09:43,383 INFO    MainThread:5845 [wandb_init.py:init():533] updated telemetry
2022-02-18 11:09:43,876 INFO    MainThread:5845 [wandb_init.py:init():563] communicating current version
2022-02-18 11:09:45,660 INFO    MainThread:5845 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.10 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-02-18 11:09:45,662 INFO    MainThread:5845 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-02-18 11:09:45,878 INFO    MainThread:5845 [wandb_init.py:init():606] starting run threads in backend
2022-02-18 11:09:50,887 INFO    MainThread:5845 [wandb_run.py:_console_start():1810] atexit reg
2022-02-18 11:09:50,888 INFO    MainThread:5845 [wandb_run.py:_redirect():1684] redirect: SettingsConsole.WRAP
2022-02-18 11:09:50,888 INFO    MainThread:5845 [wandb_run.py:_redirect():1721] Wrapping output streams.
2022-02-18 11:09:50,889 INFO    MainThread:5845 [wandb_run.py:_redirect():1745] Redirects installed.
2022-02-18 11:09:50,889 INFO    MainThread:5845 [wandb_init.py:init():633] run started, returning control to user process
2022-02-18 11:29:30,236 INFO    MainThread:5845 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 11:29:30,238 INFO    MainThread:5845 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 11:29:30,239 INFO    MainThread:5845 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_112930-2gao3dds/logs/debug.log
2022-02-18 11:29:30,239 INFO    MainThread:5845 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_112930-2gao3dds/logs/debug-internal.log
2022-02-18 11:29:30,239 INFO    MainThread:5845 [wandb_init.py:_jupyter_setup():321] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7fd316d5d510>
2022-02-18 11:29:30,240 INFO    MainThread:5845 [wandb_init.py:init():404] calling init triggers
2022-02-18 11:29:30,240 INFO    MainThread:5845 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-18 11:29:30,240 INFO    MainThread:5845 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 1jl8busg
2022-02-18 11:29:30,242 INFO    MainThread:5845 [wandb_run.py:finish():1457] finishing run simon-donike/eot_deep-learning-LeNet_v2/1jl8busg
2022-02-18 11:29:30,243 INFO    MainThread:5845 [wandb_run.py:_atexit_cleanup():1780] got exitcode: 0
2022-02-18 11:29:30,244 INFO    MainThread:5845 [wandb_run.py:_restore():1752] restore
2022-02-18 11:29:30,343 INFO    MainThread:5845 [wandb_run.py:_restore():1752] restore
2022-02-18 11:29:30,366 ERROR   MainThread:5845 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1788, in _atexit_cleanup
    self._on_finish()
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1963, in _on_finish
    self._backend.interface._publish_telemetry(self._telemetry_obj)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 67, in _publish_telemetry
    self._publish(rec)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_queue.py", line 45, in _publish
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/wandb_init.py", line 437, in init
    self._wl._global_run_stack[-1].finish()
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1463, in finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/wandb_run.py", line 1797, in _atexit_cleanup
    self._backend.cleanup()
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
2022-02-18 11:29:48,529 INFO    MainThread:5845 [wandb_setup.py:_flush():71] setting env: {}
2022-02-18 11:29:48,529 INFO    MainThread:5845 [wandb_setup.py:_flush():71] setting login settings: {}
2022-02-18 11:29:48,530 INFO    MainThread:5845 [wandb_init.py:_log_setup():371] Logging user logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_112948-2qqrn5a3/logs/debug.log
2022-02-18 11:29:48,530 INFO    MainThread:5845 [wandb_init.py:_log_setup():372] Logging internal logs to /home/simon/CDE_UBS/thesis/testing/wandb/run-20220218_112948-2qqrn5a3/logs/debug-internal.log
2022-02-18 11:29:48,530 INFO    MainThread:5845 [wandb_init.py:init():404] calling init triggers
2022-02-18 11:29:48,531 INFO    MainThread:5845 [wandb_init.py:init():411] wandb.init called with sweep_config: {}
config: {}
2022-02-18 11:29:48,531 INFO    MainThread:5845 [wandb_init.py:init():426] re-initializing run, found existing run on stack: 1jl8busg
2022-02-18 11:29:48,534 INFO    MainThread:5845 [wandb_run.py:finish():1457] finishing run simon-donike/eot_deep-learning-LeNet_v2/1jl8busg
