2022-02-25 12:46:51,544 INFO    MainThread:9652 [internal.py:wandb_internal():90] W&B internal server running at pid: 9652, started at: 2022-02-25 12:46:51.544220
2022-02-25 12:46:51,546 DEBUG   HandlerThread:9652 [handler.py:handle_request():130] handle_request: check_version
2022-02-25 12:46:51,546 INFO    WriterThread:9652 [datastore.py:open_for_write():77] open: /home/simon/CDE_UBS/thesis/template/wandb/run-20220225_124649-2chzy5bv/run-2chzy5bv.wandb
2022-02-25 12:46:51,549 DEBUG   SenderThread:9652 [sender.py:send():234] send: header
2022-02-25 12:46:51,549 DEBUG   SenderThread:9652 [sender.py:send_request():248] send_request: check_version
2022-02-25 12:46:51,663 DEBUG   SenderThread:9652 [sender.py:send():234] send: run
2022-02-25 12:46:57,809 ERROR   SenderThread:9652 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-02-25 12:46:57,810 ERROR   SenderThread:9652 [internal_api.py:execute():145] {"error":"Error 1040: Too many connections"}
2022-02-25 12:47:12,621 ERROR   SenderThread:9652 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-02-25 12:47:12,622 ERROR   SenderThread:9652 [internal_api.py:execute():145] {"error":"Error 1040: Too many connections"}
2022-02-25 12:47:12,622 ERROR   SenderThread:9652 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 147, in execute
    six.reraise(*sys.exc_info())
  File "/home/simon/.local/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 141, in execute
    return self.client.execute(*args, **kwargs)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/simon/.local/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/home/simon/.local/lib/python3.7/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2022-02-25 12:47:17,781 ERROR   SenderThread:9652 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-02-25 12:47:17,782 ERROR   SenderThread:9652 [internal_api.py:execute():145] {"error":"Error 1040: Too many connections"}
2022-02-25 12:47:21,663 DEBUG   HandlerThread:9652 [handler.py:handle_request():130] handle_request: shutdown
2022-02-25 12:47:21,664 INFO    HandlerThread:9652 [handler.py:finish():731] shutting down handler
2022-02-25 12:47:21,669 INFO    WriterThread:9652 [datastore.py:close():281] close: /home/simon/CDE_UBS/thesis/template/wandb/run-20220225_124649-2chzy5bv/run-2chzy5bv.wandb
2022-02-25 12:47:29,694 ERROR   SenderThread:9652 [internal_api.py:execute():144] 500 response executing GraphQL.
2022-02-25 12:47:29,695 ERROR   SenderThread:9652 [internal_api.py:execute():145] {"error":"Error 1040: Too many connections"}
2022-02-25 12:50:05,320 INFO    SenderThread:9652 [dir_watcher.py:__init__():169] watching files in: /home/simon/CDE_UBS/thesis/template/wandb/run-20220225_124649-2chzy5bv/files
2022-02-25 12:50:05,320 INFO    SenderThread:9652 [sender.py:_start_run_threads():807] run started: 2chzy5bv with start time 1645789609
2022-02-25 12:50:05,320 INFO    SenderThread:9652 [sender.py:finish():1070] shutting down sender
2022-02-25 12:50:05,320 INFO    SenderThread:9652 [dir_watcher.py:finish():283] shutting down directory watcher
2022-02-25 12:50:06,321 INFO    SenderThread:9652 [dir_watcher.py:finish():313] scan: /home/simon/CDE_UBS/thesis/template/wandb/run-20220225_124649-2chzy5bv/files
2022-02-25 12:50:06,321 INFO    SenderThread:9652 [dir_watcher.py:finish():327] scan save: /home/simon/CDE_UBS/thesis/template/wandb/run-20220225_124649-2chzy5bv/files/config.yaml config.yaml
2022-02-25 12:50:06,321 INFO    SenderThread:9652 [file_pusher.py:finish():177] shutting down file pusher
2022-02-25 12:50:06,321 INFO    SenderThread:9652 [file_pusher.py:join():182] waiting for file pusher
2022-02-25 12:50:06,930 INFO    Thread-10 :9652 [upload_job.py:push():137] Uploaded file /home/simon/CDE_UBS/thesis/template/wandb/run-20220225_124649-2chzy5bv/files/config.yaml
2022-02-25 12:50:07,507 INFO    MainThread:9652 [internal.py:handle_exit():77] Internal process exited
